#!/usr/bin/env python3
"""Static guard for first modern CSS support layer."""
from pathlib import Path
import sys
ROOT = Path(__file__).resolve().parents[1]
CSS = ROOT / "crates/htmlpdf-core/src/css.rs"
LAYOUT = ROOT / "crates/htmlpdf-core/src/layout.rs"
PDF = ROOT / "crates/htmlpdf-core/src/pdf.rs"
FIXTURE = ROOT / "examples/generic-modern-css.html"
FIXED_FIXTURE = ROOT / "examples/generic-fixed.html"
checks = {
    CSS: [
        "variables: BTreeMap<String, String>",
        "fn parse_custom_properties",
        "fn resolve_css_value",
        "fn strip_css_comments",
        "fn strip_important_flag",
        "important: bool",
        "fn cascade_ordered_declarations",
        "custom_properties: BTreeMap<String, String>",
        "margin_left_auto: bool",
        "margin_right_auto: bool",
        "fn parse_margin_shorthand_with_rem",
        "fn parse_two_value_margin_axis",
        "pub enum Position",
        "position: Position",
        "z_index: Option<i32>",
        "inset_top: Option<CssLength>",
        "\"position\" =>",
        "\"z-index\" =>",
        "\"inset\" =>",
        "\"top\" | \"inset-block-start\"",
        "fn parse_box_length_shorthand_with_rem",
        "fn parse_two_value_lengths",
        "fn apply_custom_properties",
        "fn is_supported_property",
        "pub enum Visibility",
        "visibility: Visibility",
        "content: Option<String>",
        "pub(crate) enum PseudoElement",
        "fn split_pseudo_element_selector",
        "fn parse_css_content_value",
        "pseudo_style_for_node",
        "fn resolve_css_value_depth",
        "fn find_var_function",
        "fn find_ascii_case_insensitive",
        "find_ascii_case_insensitive(value, \"var(\")",
        "var(",
        "pub enum CssLength",
        "pub enum JustifyContent",
        "pub enum AlignItems",
        "pub enum VerticalAlign",
        "pub enum FontStyle",
        "pub enum FontVariantNumeric",
        "font_variant_numeric: FontVariantNumeric",
        "pub struct TextDecoration",
        "pub enum TextDirection",
        "direction: TextDirection",
        "TextAlign::Justify",
        "text_align_last: Option<TextAlign>",
        "fn parse_text_align_keyword",
        "pub enum ListStyleType",
        "list_style_type: ListStyleType",
        "fn parse_list_style_type",
        '"list-style" | "list-style-type" =>',
        "pub enum GridTrack",
        "grid_tracks: Vec<GridTrack>",
        "grid_row_tracks: Vec<GridTrack>",
        "InlineFlex",
        "flex_grow: f32",
        "flex_basis: Option<CssLength>",
        "pub enum FlexWrap",
        "flex_wrap: FlexWrap",
        "align_self: Option<AlignItems>",
        "order: i32",
        '"flex" =>',
        '"flex-wrap" =>',
        '"flex-flow" =>',
        '"order" =>',
        '"align-self" =>',
        "fn parse_flex_shorthand",
        "fn parse_flex_basis",
        "fn parse_flex_wrap",
        "justify_content: JustifyContent",
        "align_content: JustifyContent",
        "align_items: AlignItems",
        "justify_items: AlignItems",
        "justify_self: Option<AlignItems>",
        "vertical_align: VerticalAlign",
        "border_spacing_horizontal: f32",
        "\"justify-content\" =>",
        "\"align-content\" =>",
        "\"justify-items\" =>",
        "\"justify-self\" =>",
        "\"align-items\" =>",
        "\"vertical-align\" =>",
        '"border-spacing" =>',
        "fn parse_border_spacing",
        "\"place-content\" =>",
        "\"place-items\" =>",
        "\"place-self\" =>",
        "fn parse_content_alignment_keyword",
        "fn parse_css_length",
        'viewport_height_pt',
        'viewport_width_pt',
        'fn parse_viewport_unit',
        "em_base_pt",
        "fn with_em_base",
        '"svh", "lvh", "dvh", "vh"',
        '"svw", "lvw", "dvw", "vw"',
        '"svi", "lvi", "dvi", "vi"',
        '"svb", "lvb", "dvb", "vb"',
        '"cqw", "cqi"',
        '"cqh", "cqb"',
        '"cqmin"',
        '"cqmax"',
        "strip_suffix(\"ex\")",
        "strip_suffix(\"cap\")",
        "strip_suffix(\"ic\")",
        "strip_suffix(\"ch\")",
        "strip_suffix(\"lh\")",
        "strip_suffix(\"rlh\")",
        '"text-wrap"',
        '"text-wrap-mode"',
        '"text-wrap-style"',
        "TextWrapStyle::Balance",
        '"pre-line" => self.white_space = WhiteSpace::PreLine',
        '"white-space-collapse"',
        "fn parse_word_spacing_with_rem",
        "fn parse_relative_rgb_color",
        "fn parse_css_color_function",
        "fn display_p3_to_srgb",
        "rgb(from",
        "color(display-p3",
        "lh_base_pt",
        "rlh_base_pt",
        "fn with_lh_base",
        "fn css_ch_unit_pt",
        "fn css_ex_unit_pt",
        "fn css_cap_unit_pt",
        "fn css_ic_unit_pt",
        "fn parse_calc_length_with_rem",
        "fn parse_env_length_fallback",
        "strip_css_function(value.trim(), \"env\")",
        "CssLength::points(0.0)",
        "fn reset_all_except_custom_properties",
        "fn is_zero_rect_clip",
        '"all" =>',
        '"clip" =>',
        "pub enum BackgroundClip",
        "background_clip: BackgroundClip",
        "fn parse_background_clip",
        "fn parse_background_clip_from_shorthand",
        '"background-clip" =>',
        "aspect_ratio: Option<f32>",
        '"aspect-ratio" =>',
        "max_height: Option<CssLength>",
        '"max-block-size"',
        "fn parse_aspect_ratio",
        "fn parse_grid_track",
        "fn parse_fr_unit",
        "grid_column_start: Option<usize>",
        "grid_column_end: Option<usize>",
        "grid_column_span: usize",
        "grid_row_start: Option<usize>",
        "grid_row_end: Option<usize>",
        "grid_row_span: usize",
        '"grid-template-rows" =>',
        '"grid-column" =>',
        '"grid-column-start" =>',
        '"grid-column-end" =>',
        '"grid-row" =>',
        '"grid-row-start" =>',
        '"grid-row-end" =>',
        "fn parse_grid_column_placement",
        "fn parse_grid_line_span",
        "fn parse_grid_positive_line",
        "rem_base_pt",
        "CssLength::Clamp",
        "fn parse_linear_gradient",
        "angle_deg",
        "pub struct GradientStop",
        "stops: Vec<GradientStop>",
        "fn parse_gradient_stop_position",
        "fn normalize_gradient_stops",
        "fn parse_linear_gradient_angle",
        "pub struct RadialGradient",
        "fn parse_radial_gradients",
        "fn parse_radial_gradient_layer",
        "fn parse_radial_gradient_center",
        "find(|layer| layer.starts_with(\"linear-gradient(\"))",
        "background_gradient",
        "background_radials",
        "fn parse_background_shorthand_geometry",
        "fn normalize_background_slash_outside_functions",
        "strip_suffix(\"rem\")",
        "strip_suffix(\"em\")",
        "fn parse_rgb_color",
        "fn parse_hwb_color",
        "fn hwb_to_srgb",
        "fn parse_rgb_channel",
        "fn parse_alpha_channel",
        "fn parse_color_or_current",
        "fn parse_lab_color",
        "fn parse_lch_color",
        "fn parse_border_shorthand_with_current",
        '"opacity" =>',
        '"font" =>',
        "fn apply_font_shorthand",
        "line_height_is_normal: bool",
        "fn parse_font_size_token",
        "fn parse_font_weight_token",
        "fn parse_font_style_token",
        "fn parse_font_variant_numeric",
        "fn font_feature_settings_enable_tabular_numbers",
        "fn parse_text_decoration_line",
        '"font-style" =>',
        '"font-variant-numeric" =>',
        '"font-feature-settings" =>',
        '"direction" =>',
        '"justify" | "justify-all" => Some(TextAlign::Justify)',
        '"text-align" | "text-align-all" =>',
        '"text-align-last" =>',
        '"text-decoration" | "text-decoration-line" =>',
        "transform_translate_x: Option<CssLength>",
        "transform_origin_x: CssLength",
        "transform_scale_x: f32",
        "fn parse_css_transform",
        "fn parse_transform_functions",
        "fn parse_transform_origin",
        "fn parse_translate_property",
        "fn parse_scale_property",
        "fn parse_rotate_value",
        "overflow_hidden",
        '"overflow" | "overflow-x" | "overflow-y"',
        "object_position_x: f32",
        '"object-position" =>',
        "pub fn with_opacity",
        "fn extract_css_color",
        "fn parse_color_mix",
        "fn parse_color_mix_space",
        "fn mix_colors_in_space",
        "fn srgb_to_lab",
        "fn srgb_to_oklab",
        "fn parse_color_mix_stop",
        "fn supports_query_matches",
        "selector.starts_with(\"@supports\")",
        "selector_lower.starts_with(\"@media\")",
        "selector_lower.starts_with(\"@supports\")",
        "selector.starts_with(\"@layer\")",
        "struct CascadeLayerAccumulator",
        "fn register_cascade_layer_statements",
        "fn parse_layer_block_name",
        "layers.push_layer_chunk",
        "layer_index: Option<usize>",
        "fn important_rule_cascade_key",
        "fn ordered_rule_declarations",
        "fn inherited_from",
        "fn apply_user_agent_defaults",
        "pub enum WhiteSpace",
        "PreLine",
        "pub enum TextWrapStyle",
        "text_wrap_style: TextWrapStyle",
        "pub enum TextOverflow",
        "text_overflow: TextOverflow",
        "word_spacing: f32",
        "text_decoration_color: Option<Color>",
        "text_decoration_thickness: Option<f32>",
        "text_underline_offset: Option<f32>",
        '"text-overflow" =>',
        '"text-align-last"',
        '"text-align-all"',
        '"word-spacing" =>',
        '"text-decoration-color" =>',
        '"text-decoration-thickness" =>',
        '"text-underline-offset" =>',
        "fn parse_text_decoration_thickness",
        "fn parse_text_underline_offset",
        "pub enum OverflowWrap",
        "padding-inline",
        "border-inline-start",
        "inline-size",
        "min-block-size",
        "fn parse_hsl_color",
        "fn parse_lab_color",
        "fn parse_lch_color",
        "fn parse_oklch_color",
        "fn parse_oklab_color",
        "fn parse_named_color",
        "fn linear_srgb_to_srgb",
        "pub struct BoxShadow",
        "box_shadows: Vec<BoxShadow>",
        "fn parse_box_shadows_with_rem",
        "fn parse_box_shadow_layer_with_rem",
        "fn parse_box_shadow_with_rem",
        "text_shadow: Option<BoxShadow>",
        "fn parse_text_shadow_with_rem",
        "fn parse_drop_shadow_filter_with_rem",
        "fn parse_border_radius_with_rem",
        "fn parse_border_line_style",
        "outline_width: f32",
        "outline_offset: f32",
        "fn parse_outline_width",
        "fn parse_outline_line_style",
        '"outline" =>',
        '"outline-offset" =>',
        '"cursor"',
        '"user-select"',
        '"pointer-events"',
        '"transition"',
        '"animation"',
        '"will-change"',
        '"appearance"',
        '"backdrop-filter"',
        '"-webkit-backdrop-filter"',
        '"touch-action"',
        '"-webkit-user-select"',
        '"-webkit-text-size-adjust"',
        '"-webkit-tap-highlight-color"',
        '"text-rendering"',
        '"font-kerning"',
        '"font-optical-sizing"',
        '"font-synthesis"',
        '"color-scheme"',
        '"print-color-adjust"',
        '"container-type"',
        '"overscroll-behavior"',
        '"scroll-behavior"',
        '"accent-color"',
        '"caret-color"',
        '"resize"',
        '"z-index"',
        '"isolation"',
        "border-top-left-radius",
        "border-block-width",
        "border-inline-color",
        "\"box-shadow\"",
        "\"filter\"",
        "fn expand_nested_css",
        "fn expand_nested_rule",
        "fn combine_nested_selectors",
        "fn expand_selector_list_functions",
        "fn find_selector_function_call",
        "find_selector_function_call(&selector, &[\":is\", \":where\"])",
        "fn selector_specificity_for_cascade",
        "extract_selector_function(rest, &[\":where\"])",
        "fn max_selector_list_specificity",
        "AttributeCaseSensitivity::AsciiInsensitive",
        "eq_ignore_ascii_case",
        "fn parse_has_selectors",
        "has_selectors: Vec<RelativeSelector>",
        "not_selectors: Vec<Selector>",
        "struct RelativeSelector",
        "fn normalize_relative_has_selector",
        "matches_in_descendants",
        "fn parse_pseudo_classes",
        "PseudoClass::Disabled",
        "PseudoClass::Enabled",
        "PseudoClass::Checked",
        "PseudoClass::Default",
        "PseudoClass::PlaceholderShown",
        "PseudoClass::Lang",
        "PseudoClass::Dir",
        "struct NthChildSelector",
        "fn parse_nth_child_selector",
        "fn split_nth_child_of_selector",
        "fn element_sibling_position_matching",
        "fn is_disabled_form_control",
        "fn is_checked_control",
        "fn is_default_form_control",
        "fn is_placeholder_shown",
        "fn inherited_language",
        "fn language_matches",
        "fn inherited_direction",
        "fn parse_language_ranges",
        "fn parse_direction_pseudo",
        "fn contains_unsupported_pseudo_element",
        "fn flatten_scoped_css",
        "fn prefix_scoped_rules",
        "fn scoped_selector",
        "fn parse_registered_custom_property_initials",
        "fn collect_registered_custom_property_initials",
        "fn eval_supports_condition",
        "fn split_supports_top_level_keyword",
        "fn supports_property_value",
        "height_px: f32",
        "fn single_media_query_matches",
        "fn media_orientation",
        "fn media_feature_value_matches",
        "fn parse_media_feature_value",
        '"hover"',
        '"any-hover"',
        '"pointer"',
        '"any-pointer"',
        '"update"',
        '"color-gamut"',
        "fn parse_media_size_range_constraint",
        "fn parse_media_size_constraint",
        '"hyphens"',
        '"-webkit-hyphens"',
        '"-moz-hyphens"',
        '"-moz-orient"',
        "fn parse_media_width_range_constraint",
        "fn parse_light_dark_color",
        "selector_lower.starts_with(\"@container\")",
        "fn container_query_matches",
    ],
    LAYOUT: [
        "struct ContainingBlock",
        "containing_blocks: Vec<ContainingBlock>",
        "fn layout_positioned_node",
        "fixed_overlays: Vec<Vec<LayoutItem>>",
        "fn register_fixed_overlay",
        "fn start_new_page",
        "fn relative_position_offset",
        "fn apply_relative_position_to_range",
        "fn apply_relative_position_to_following_pages",
        "fn positioned_width",
        "fn positioned_height",
        "fn is_out_of_flow_position",
        "fn is_positioned_containing_block",
        "fn positioned_z_index",
        "fn reorder_paint_stack_ranges",
        "fn prepend_document_background",
        "fn insert_continuation_background_fragments",
        "fn print_margin_masks",
        "options.page.margin_left_pt",
        "options.page.margin_bottom_pt",
        "fn find_first_element_by_tag",
        "fn push_radial_background_items",
        "fn radial_gradient_image",
        "fn raster_gradient_axis_px",
        "ImageFormat::Raw",
        "LayoutItem::BeginClip",
        "LayoutItem::EndClip",
        "fn flex_row_spacing",
        "fn flex_cross_axis_shift",
        "fn flex_row_intrinsic_width",
        "fn truncate_text_with_ellipsis",
        "fn grid_track_widths",
        "struct GridPlacedChild",
        "fn grid_auto_placement_rows",
        "fn grid_spanned_track_width",
        "fn grid_row_track_min_height",
        "fn grid_track_inline_distribution",
        "fn grid_content_cross_axis_row_offset",
        "fn align_grid_rows_cross_axis",
        "fn grid_item_inline_geometry",
        "fn adjusted_grid_column_offset",
        "fn flex_line_ranges",
        "fn distribute_flex_grow",
        "fn shift_layout_items",
        "fn apply_style_transform_to_range",
        "fn scale_layout_items",
        "fn transform_origin_point",
        "fn scale_point",
        "fn resolve_flow_horizontal_geometry",
        "FlowHorizontalGeometry",
        "fn resolved_text_align",
        "fn can_collapse_adjacent_sibling_margin",
        "fn resolved_line_text_align",
        "fn suppress_justify_spacing_for_line",
        "fn justified_inline_word_spacing",
        "fn justified_word_spacing",
        "fn resolve_box_height",
        "fn intrinsic_inline_width",
        "fn first_text_baseline_offset",
        "max_baseline_offset",
        "VerticalAlign::Middle",
        "fn table_horizontal_spacing",
        "fn table_vertical_spacing",
        "content_height: f32",
        "fn paint_snapshot",
        "fn restore_paint_snapshot",
        "Visibility::Hidden",
        "PseudoElement::Before",
        "push_pseudo_inline_segment",
        "fn layout_generated_pseudo_box",
        "fn paint_positioned_generated_pseudos",
        "fn paint_generated_pseudo_box_in_containing_block",
        "fn has_generated_pseudo_box_paint",
        "fn layout_form_control",
        "fn is_rendered_form_control",
        "fn form_control_box_size",
        "fn selected_option_text",
        "fn soft_break_word_to_fill_line",
        "fn browser_wrap_width_factor",
        "available_width >= 430.0",
        "(font_size - 15.0).abs() < 0.01",
        "fn layout_line_height",
        "fn balance_text_lines_with_face",
        "fn collapse_pre_line_whitespace_for_layout",
        "line_height_is_normal",
        "style.font_size * 1.065",
        "fn rotate_layout_items_from",
        "fn rotate_point",
        "fn push_list_marker_segment",
        "fn ordered_list_item_index",
        "ListStyleType::Decimal",
        "fn push_container_outline",
        "fn outline_stroke_rect",
        "fn has_outline",
        "fn push_box_shadow_items",
        "fn push_box_shadow_layer",
        "style.box_shadows.iter().rev().copied()",
        "fn background_clip_rect",
        "BackgroundClip::PaddingBox",
    ],
    PDF: [
        "ClipRect",
        "fn push_clip_rect",
        "fn push_gradient_cell",
        "fn gradient_color",
        "fn native_linear_shading_supported",
        "fn linear_shading_dictionary",
        "/Shading <<",
        "sh Q",
        "stops.windows(2)",
        "W n",
        "ExtGState",
        "/ca {} /CA {}",
        "fn alpha_graphics_state",
        "alpha.clamp(0.0, 1.0)",
        "FontStyle::Italic | FontStyle::Oblique",
        "fn text_transform_matrix",
        "fn push_text_decoration",
        "text.text_decoration_color.unwrap_or(color)",
        ".text_decoration_thickness",
        ".text_underline_offset",
    ],
    FIXTURE: [
        "--brand: rgb(37 99 235)",
        "Build-tool comments should be ignored",
        "color: var(--ink) !important",
        "position: relative",
        "position: absolute",
        "right: 1rem",
        "--accent: oklch(70.7% .165 254.624)",
        "inline-size: min(100%, 42rem)",
        "min-block-size: clamp(9rem, calc(7rem + 6rem), 14rem)",
        "linear-gradient(135deg, var(--surface) 0%, rgb(219 234 254) 52%, rgb(255 255 255) 100%)",
        "radial-gradient",
        "border: 2px solid var(--fallback-brand)",
        "border-inline-start: 0.4rem solid hsl(199 89% 48%)",
        "overflow: hidden",
        "font-size: clamp(1.6rem, 2rem, 2.4rem)",
        "color: VAR(--brand)",
        "@MEDIA print",
        "uppercase-at-rule-modern",
        "padding: calc(0.5rem + 0.25rem) 1rem",
        "padding-inline: calc(1rem + 0.5rem)",
        "0 1rem 2rem rgba(15, 23, 42, 0.16)",
        "0 0.25rem 0.75rem rgb(37 99 235 / 8%)",
        "text-shadow: 0 1px 2px rgb(15 23 42 / 70%)",
        "generated-modern::before",
        "content: \"Generated before · \"",
        "generated-modern::after",
        ".pseudo-box-modern::before",
        "content: \"\"",
        "display: block",
        "block-size: 0.35rem",
        ".pseudo-box-modern::after",
        "position: absolute",
        "inset-block-start: 0.7rem",
        "radial-gradient(circle at 35% 35%",
        "--wash: color-mix(in srgb, var(--brand), transparent 92%)",
        "--fallback-brand: var(--missing-brand, var(--brand))",
        "--media-ratio: 16 / 9",
        "border-color: #2563eb33",
        "@supports (color: color-mix(in srgb, red, transparent))",
        "border-left-color: color-mix(in lab, lab(62% 18 -28) 30%, white)",
        "@layer components",
        ".layer-cascade-modern",
        "@layer utilities",
        "Unlayered declarations should outrank later normal @layer declarations.",
        "@layer reset, components",
        ".named-layer-modern",
        "Named cascade-layer order should outrank source order",
        ".important-layer-modern",
        "Important layered declarations should reverse named layer order",
        "opacity: 0.72",
        "white-space: nowrap",
        "text-wrap: pretty",
        "text-wrap-mode: wrap",
        "text-wrap-style: balance",
        "white-space-collapse: collapse",
        "text-overflow: ellipsis",
        "max-inline-size: 60ch",
        "overflow-wrap: anywhere",
        "justify-content: space-between",
        "align-items: center",
        "justify-content: space-evenly",
        "align-items: baseline",
        "flex-wrap: wrap",
        "flex-flow: row wrap",
        "order: -1",
        "align-self: flex-end",
        "flex: 1 1 0",
        "flex: 0 0 8rem",
        "max-block-size: 12rem",
        "place-items: center start",
        "grid-column: span 2 / span 2",
        "grid-column: 1 / -1",
        "font: italic 650 1rem/1.5 Georgia, serif",
        "font-style: oblique 12deg",
        "font-variant-numeric: lining-nums tabular-nums",
        'font-feature-settings: "kern" 1, "tnum" 1',
        "text-decoration: underline line-through",
        "text-decoration-color: color-mix(in srgb, var(--brand), transparent 15%)",
        "text-decoration-thickness: 0.12em",
        "text-underline-offset: 0.18em",
        "color: oklab(52% 0.03 -0.1 / 90%)",
        "background-color: lch(96% 8 260deg / 60%)",
        "border-bottom: 2px solid lab(62% 18 -28 / 70%)",
        "border-block-width: 2px 4px",
        "border-inline-color: tomato gold",
        "border-radius: 12px 4px / 6px 2px",
        "outline: 4px dashed currentColor",
        "outline-offset: 3px",
        "all: initial",
        ".all-initial-modern",
        "clip: rect(0 0 0 0)",
        ".clip-hidden-modern",
        "list-style: none",
        "list-style-type: none",
        "background-clip: padding-box",
        "backdrop-filter: blur(8px)",
        "touch-action: manipulation",
        "text-rendering: geometricPrecision",
        "font-optical-sizing: auto",
        "container-type: inline-size",
        "@supports ((-webkit-hyphens: none) and (not (margin-trim: inline)))",
        "@property --registered-alpha",
        "initial-value: 72%",
        "opacity: var(--registered-alpha)",
        "overscroll-behavior: contain",
        "accent-color: currentColor",
        "isolation: isolate",
        "z-index: 2",
        "z-index should order positioned sibling layers",
        "transition: color 120ms ease",
        "print-color-adjust: exact",
        "translate: 0.25rem -0.15rem",
        "scale: 98%",
        "rotate: 0.01turn",
        "transform-origin: left top",
        "transform: translateX(0.4rem) translateY(-0.2rem) scale(0.98, 1.02) rotate(2deg)",
        "aspect-ratio: var(--media-ratio)",
        "padding: 0.75em 1em",
        'background: url("assets/generic-photo.jpg") right bottom / cover no-repeat #eff6ff',
        "table-align-modern",
        "border-spacing: 0.25rem 0.5rem",
        "vertical-align: middle",
        'margin-block-start: 1svh',
        'padding: calc(var(--viewport-rhythm) + 0.25rem) 2vmax',
        'min-block-size: max(8dvh, 4rem)',
        'inline-size: min(40vw, 18rem)',
        '--viewport-rhythm: 1vmin',
        'padding-inline: calc(env(safe-area-inset-left, 2px) + 1rem)',
        'padding-block-start: env(safe-area-inset-top, 0.5rem)',
        'margin-block-start: env(safe-area-inset-bottom)',
        "env() safe-area variables should resolve length fallbacks in static print, including inside calc().",
        "padding-block: 1lh",
        "margin-block-start: 0.5rlh",
        "inline-size: calc(10lh + 2rlh)",
        "lh and rlh units should resolve from element and root line-height contexts.",
        ".font-logical-units-modern",
        "padding-inline: 2ex 1cap",
        "block-size: 3ic",
        "inline-size: calc(12vi + 2vb + 3cap)",
        "max-inline-size: min(50cqw, 24rem)",
        "min-block-size: max(8cqh, 3ic)",
        "padding-block-start: calc(2cqi + 0.25rem)",
        "margin-block-start: 1svi",
        "margin-block-end: calc(1cqmin + 0.25rem)",
        "text-wrap: pretty",
        "text-wrap-mode: wrap",
        "text-wrap-style: balance",
        "white-space-collapse: collapse",
        "word-spacing: 0.18em",
        "color: rgb(from oklch(42% 0.11 252 / 92%) r g b / alpha)",
        "border: 1px solid rgb(from color(display-p3 0.55 0.7 1) r g b / 38%)",
        "box-shadow: 0 0 0 2px hwb(218 15% 12% / 18%)",
        "background: color(display-p3 0.97 0.985 1 / 84%)",
        "word-spacing, rgb(from ...), hwb(...), and color(display-p3 ...)",
        ":is(.unused-selector, .functional-selector)",
        ".modern-card :where(.missing-selector, .selector-modern)",
        '.selector-modern[data-state="browser-match" i]',
        '.selector-modern[data-flags~="READY" i]',
        ".modern-card :not(.legacy-shell .complex-not-modern, .complex-not-modern.excluded)",
        "Complex :not() selector lists should support modern framework exclusion rules.",
        ".filtered-nth-modern > li:nth-child(even of .visible-row)",
        "Second visible row should be highlighted by nth-child(of selector)",
        ".language-dir-modern:lang(es)",
        ".language-dir-modern .rtl-chip:dir(rtl)",
        ".language-dir-modern .ltr-chip:dir(ltr)",
        'lang="es-ES"',
        "selector-modern functional-selector",
        'data-state="Browser-Match"',
        ".modern-card:has(.selector-modern)",
        ".form-state-modern input:disabled + .disabled-label",
        ".form-state-modern input:enabled + .enabled-label",
        ".form-state-modern input:checked + .checked-label",
        ".form-state-modern input:default + .default-label",
        ".form-state-modern option:default",
        ".form-state-modern input:required + .required-label",
        ".form-state-modern input:optional + .optional-label",
        ".form-state-modern input:placeholder-shown + .placeholder-label",
        ".form-state-modern input:hover + .dynamic-label",
        ".form-state-modern input::-webkit-slider-thumb",
        ":hover/:focus/:active must not be faked in static PDF output.",
        "light-dark(rgb(37 99 235), rgb(15 23 42))",
        "@scope (.scoped-region)",
        ".scoped-target",
        "@media (width >= 30rem)",
        ".range-query",
        "@media ((prefers-color-scheme: dark) or (width >= 30rem))",
        ".or-query",
        "@media (orientation: portrait) and (prefers-color-scheme: light) and (prefers-reduced-motion: no-preference)",
        "@media (hover: none) and (pointer: none) and (update: none) and (color-gamut: srgb)",
        ".media-interaction-modern",
        "@media (prefers-color-scheme: dark), (orientation: landscape), (prefers-reduced-motion: reduce)",
        ".media-preference-modern",
        "Static print media should prefer light color scheme, portrait orientation, and no-preference motion.",
        "Static PDF media should expose no hover, no pointer, no update loop, and sRGB color gamut.",
        "border: 2px solid currentColor",
        "background-color: rgb(255 255 255 / 80%)",
        "rgba(71, 85, 105, 0.92)",
        "& .nested-badge",
        ".scoped-vars",
        "--local-pill: var(--missing-pill, hsl(199 89% 48%))",
        "@container (min-width: 20rem)",
        ".container-enhanced",
    ],
    FIXED_FIXTURE: [
        "position: fixed",
        "Fixed header",
        "Fixed footer",
        "<p>alpha bravo charlie",
    ],
}
errors = []
for path, tokens in checks.items():
    if not path.exists():
        errors.append(f"missing required file: {path.relative_to(ROOT)}")
        continue
    text = path.read_text()
    for token in tokens:
        if token not in text:
            errors.append(f"missing `{token}` in {path.relative_to(ROOT)}")
if errors:
    print("generic modern CSS support audit failed:", file=sys.stderr)
    for error in errors:
        print(f"- {error}", file=sys.stderr)
    sys.exit(1)
print("generic modern CSS support audit passed")
